on:
  issue_comment:
    types: [ created, edited, deleted ]


jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build')}}
    runs-on: ubuntu-latest

    # Build steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.issue}}
      - run: echo test
