on:
  issue_comment:
    types: [ created, edited, deleted ]


jobs:
  build:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/build')}}
    runs-on: ubuntu-latest

    # Build steps
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: test
      - run: echo ${{ github.event.issue.pull_request }}
